providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "python manage.py collectstatic --no-input",
    "python manage.py migrate"
]

[start]
cmd = "gunicorn core.wsgi --bind 0.0.0.0:$PORT --log-file -"
